<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Hastalk zni</name>
   <tag></tag>
   <elementGuidId>a3782a54-2af6-45bc-9c58-995ab0aad811</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='AbsenceTypeValue_431382ca-525f-4824-9eff-a8d40675b7b7']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#AbsenceTypeValue_431382ca-525f-4824-9eff-a8d40675b7b7 > div.ant-select-item-option-content</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>eecc3782-dac0-488c-a687-db25f37ba1c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-select-item-option-content</value>
      <webElementGuid>53c9979d-79b1-4080-a0a7-f1d59c5f3964</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hastalık İzni</value>
      <webElementGuid>b0a80866-7aee-441a-8828-56ab70a18ba8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AbsenceTypeValue_431382ca-525f-4824-9eff-a8d40675b7b7&quot;)/div[@class=&quot;ant-select-item-option-content&quot;]</value>
      <webElementGuid>cc9f4ffa-99d2-4b48-9218-37d601ee0232</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='AbsenceTypeValue_431382ca-525f-4824-9eff-a8d40675b7b7']/div</value>
      <webElementGuid>51bffc89-e34c-4284-8c17-964ab4709766</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Evlilik İzni'])[1]/following::div[2]</value>
      <webElementGuid>5a6af1e4-d9f2-4b62-b8c6-ba9d72c8436f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yıllık İzin'])[1]/following::div[4]</value>
      <webElementGuid>a673104e-0b8f-457c-8e31-31da7a058bcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Babalık İzni'])[1]/preceding::div[1]</value>
      <webElementGuid>b59f733d-8549-4cba-80e2-e6d817bd84df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Doğum İzni'])[1]/preceding::div[3]</value>
      <webElementGuid>2c2b0d03-fa7f-4592-afcb-77f36a917707</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Hastalık İzni']/parent::*</value>
      <webElementGuid>c3e75bf3-5a97-4ca6-99cb-4b1f00b1281d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[3]/div</value>
      <webElementGuid>045fd6a3-6032-44e9-b579-467c3c5716f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Hastalık İzni' or . = 'Hastalık İzni')]</value>
      <webElementGuid>a5eac398-9bf6-4509-b475-a51e47484802</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
