<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Doum zni</name>
   <tag></tag>
   <elementGuidId>b8e82a13-6e78-4606-81b1-011d1cae0ba7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='AbsenceTypeValue_8ced2333-6169-4f60-b2b5-3737dfd8a336']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#AbsenceTypeValue_8ced2333-6169-4f60-b2b5-3737dfd8a336 > div.ant-select-item-option-content</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9eb37a1b-7495-459e-aed1-f3e8c2e70910</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-select-item-option-content</value>
      <webElementGuid>35562267-fa68-4cfc-9516-2135e85db901</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Doğum İzni</value>
      <webElementGuid>6eaf155b-ff6c-479a-88e8-8231a010b146</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AbsenceTypeValue_8ced2333-6169-4f60-b2b5-3737dfd8a336&quot;)/div[@class=&quot;ant-select-item-option-content&quot;]</value>
      <webElementGuid>892f92e2-410a-4ea7-99cd-593f42e1e574</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='AbsenceTypeValue_8ced2333-6169-4f60-b2b5-3737dfd8a336']/div</value>
      <webElementGuid>b1cf630d-40be-47a8-9ab9-5fc0cc5e0e4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Babalık İzni'])[1]/following::div[2]</value>
      <webElementGuid>2fc6f2f5-3fc3-4741-837d-f15167d59458</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hastalık İzni'])[1]/following::div[4]</value>
      <webElementGuid>bbf79152-2a8b-4ba1-bca6-c74f29718541</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vefat İzni'])[1]/preceding::div[1]</value>
      <webElementGuid>ccbb8493-380d-4e01-9d76-5f183fc3340f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Doğum İzni']/parent::*</value>
      <webElementGuid>2ede7cf2-0abb-4a49-94e8-f67fdad93ef5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div[5]/div</value>
      <webElementGuid>d3db3cc3-1534-42ba-b20a-f9620fb1b68d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Doğum İzni' or . = 'Doğum İzni')]</value>
      <webElementGuid>b04fb0ac-3cca-4832-b70a-b0b835c84203</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
