<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Vefat zni</name>
   <tag></tag>
   <elementGuidId>16b70668-f8df-4e37-b2ca-83f317bab582</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='AbsenceTypeValue_ac1c0669-04d5-4bba-909b-cc80a59cdc35']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#AbsenceTypeValue_ac1c0669-04d5-4bba-909b-cc80a59cdc35 > div.ant-select-item-option-content</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7031e870-2472-43aa-b39c-2d2dd52b5840</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-select-item-option-content</value>
      <webElementGuid>01a60f8c-bbb9-490e-bfee-c9d5a893856f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Vefat İzni</value>
      <webElementGuid>206df632-00e8-41d8-a1ee-9223a6bd5013</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AbsenceTypeValue_ac1c0669-04d5-4bba-909b-cc80a59cdc35&quot;)/div[@class=&quot;ant-select-item-option-content&quot;]</value>
      <webElementGuid>4e5545e4-e8c7-4786-b6d2-fd3673937828</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='AbsenceTypeValue_ac1c0669-04d5-4bba-909b-cc80a59cdc35']/div</value>
      <webElementGuid>0394645c-7561-40ca-bbe6-cc73f8cb974f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Doğum İzni'])[1]/following::div[2]</value>
      <webElementGuid>ae5db1a5-2169-4c6a-b3a9-8650f2366810</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Babalık İzni'])[1]/following::div[4]</value>
      <webElementGuid>7cd61759-e76c-4959-9e4a-41dc3caf9841</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Vefat İzni']/parent::*</value>
      <webElementGuid>4645734d-2b9f-4560-8a38-1f2823e3c5d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div[6]/div</value>
      <webElementGuid>38229327-23cb-4d69-a3fd-153a1f20b215</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Vefat İzni' or . = 'Vefat İzni')]</value>
      <webElementGuid>14d033ed-de18-454a-acb3-a58062360c9c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
