<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Yllk zin</name>
   <tag></tag>
   <elementGuidId>099df09b-0243-467a-94aa-93eeaa186546</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='AbsenceTypeValue_c394268b-e895-4b28-a978-325396aa2080']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.ant-select-item-option-content</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b3a27a91-cc4e-4ecc-adb5-9aec75c16985</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-select-item-option-content</value>
      <webElementGuid>cdb84ebe-3771-49c9-9e3a-ab096cc7add9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Yıllık İzin</value>
      <webElementGuid>12acac3f-f344-4a60-9d98-f0d27df52dea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AbsenceTypeValue_c394268b-e895-4b28-a978-325396aa2080&quot;)/div[@class=&quot;ant-select-item-option-content&quot;]</value>
      <webElementGuid>003f7238-3eae-4b84-bc88-e22374dadbab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='AbsenceTypeValue_c394268b-e895-4b28-a978-325396aa2080']/div</value>
      <webElementGuid>61a034a0-51da-4b99-b792-8aae918966a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='c394268b-e895-4b28-a978-325396aa2080'])[1]/following::div[7]</value>
      <webElementGuid>a5d529e6-ac1d-4b18-8d5a-f9b62ec9d521</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[2]/following::div[14]</value>
      <webElementGuid>a6305aa3-b39f-40cb-b9c3-7fbf9fa5be79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Evlilik İzni'])[1]/preceding::div[1]</value>
      <webElementGuid>4be3f93c-cda3-44c6-b779-1b37a2ebb43d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hastalık İzni'])[1]/preceding::div[3]</value>
      <webElementGuid>1b02ebce-05fe-4c54-91f9-e09580ecc91e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Yıllık İzin']/parent::*</value>
      <webElementGuid>1279e0ec-2c79-4175-8cea-06cd8c5fba33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div[2]/div/div/div/div/div</value>
      <webElementGuid>eb7f0a24-0d81-4bed-a200-a3226f8a45a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Yıllık İzin' or . = 'Yıllık İzin')]</value>
      <webElementGuid>edf38573-6d4c-4c62-a812-961faf5ea0c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
