<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Balang Tarihi_BeginDate</name>
   <tag></tag>
   <elementGuidId>437af5c4-553d-4635-bc38-756bef5a943a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='BeginDate']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#BeginDate</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>367ceb5a-699d-4ec8-a468-00ba2127f013</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BeginDate</value>
      <webElementGuid>1317edf5-fbda-453f-b546-c55b3fc79e90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Tarih Giriniz</value>
      <webElementGuid>490ddb5b-4f5d-4ed6-b014-338cf3e18c23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>21</value>
      <webElementGuid>1b9d5fd7-ada2-406a-ac14-b322538009be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>1a88667f-94ec-4d62-85fd-d119a1e8ef8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BeginDate&quot;)</value>
      <webElementGuid>cd86793d-d158-4995-8581-dba8cdf749a9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='BeginDate']</value>
      <webElementGuid>4eccc6cb-d651-4098-bbf3-4d697d760ee7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Column_q$U_xbm8']/div/div[2]/div/div/div/div/input</value>
      <webElementGuid>e1b6047c-7432-48ca-9c75-da2ad5dc60b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]/div/div/div/div/input</value>
      <webElementGuid>45d4f4b9-a532-4e19-a1da-e85b336af921</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'BeginDate' and @placeholder = 'Tarih Giriniz']</value>
      <webElementGuid>8a736545-c8c6-41f5-a26c-5f214db669d1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
